---
## This playbook deploys the whole application stack in this site.  

# deploy dnsmasq
- hosts: hypervisors
  become: yes
  become_user: root
  roles:
    - ovirt-engine-export-local-nfs
    - ovirt-engine-add-storage