---
## This playbook deploys the whole application stack in this site.  

- hosts: all
  become: yes
  vars:
    #engine_url: https://{{ ovirt_engine_fqdn | default(ansible_fqdn) }}/ovirt-engine/api
    #engine_user: admin@internal
    #engine_password: "{{ ansible_password }}"
    #engine_cafile: /etc/pki/ovirt-engine/ca.pem

    qcow_url: http://192.168.1.21:8000/win10_pro_n_1803_100gb_template.qcow2
    template_cluster: 192-168-1-70-Local
    template_name: win10_pro_n_1803_100gb
    template_memory: 4GiB
    template_cpu: 2
    template_disk_size: 100GiB
    template_disk_storage: data
    template_disk_format: cow

  roles:
    - ovirt.image-template
