---

- hosts: all
  become: yes
  vars:
    engine_url: https://{{ ovirt_engine_fqdn | default(ansible_fqdn) }}/ovirt-engine/api
    engine_user: admin@internal
    engine_password: '{{ ansible_password | default(ansible_ssh_password) | b64encode | b64decode }}'
    engine_cafile: /etc/pki/ovirt-engine/ca.pem

    data_center_name: mydatacenter
    data_center_local: true
    compatibility_version: 4.3

    qcow_url: https://cloud.centos.org/centos/7/images/CentOS-7-x86_64-GenericCloud.qcow2
    template_cluster: production
    template_name: centos7_template
    template_memory: 4GiB
    template_cpu: 2
    template_disk_size: 10GiB
    template_disk_storage: data_domain

    clusters:
      - name: production
        cpu_type: Intel SandyBridge Family
        profile: production

    hosts:
      - name: "{{ ansible_host }}"
        address: "{{ ansible_host }}"
        cluster: production
        password: '{{ ansible_password | default(ansible_ssh_password) | b64encode | b64decode }}'

    storages:
      data_domain:
        master: true
        state: present
        localfs:
          path: /data
      export_domain:
        domain_function: export
        nfs:
          address: "{{ ansible_host }}"
          path: /export/import_export
      iso_domain:
        domain_function: iso
        nfs:
          address: "{{ ansible_host }}"
          path: /export/iso

#    logical_networks:
#      - name: ovirtmgmt
#        clusters:
#          - name: production
#            assigned: yes
#            required: no
#            display: no
#            migration: yes
#            gluster: no
#
#    host_networks:
#      - name: "{{ ansible_host }}"
#        check: true
#        save: true
#        networks:
#          - name: ovirtmgmt
#            boot_protocol: dhcp


  pre_tasks:
    - name: Login to oVirt
      ovirt_auth:
        url: "{{ engine_url }}"
        username: "{{ engine_user }}"
        password: "{{ engine_password }}"
        ca_file: "{{ engine_cafile | default(omit) }}"
        insecure: "{{ engine_insecure | default(true) }}"
      tags:
        - always

  tasks:
    - include_role:
        name: ovirt-engine-export-local-nfs

    - name: ensure local storage dir exists
      file:
        path: /data
        state: directory
        owner: vdsm
        group: kvm

    - block:
        - include_role:
            name: ovirt.infra
      rescue:
        # retry the same role
        - include_role:
            name: ovirt.infra

    - include_role:
        name: ovirt.image-template

  post_tasks:
    - name: Logout from oVirt
      ovirt_auth:
        state: absent
        ovirt_auth: "{{ ovirt_auth }}"
      tags:
        - always