---

- hosts: all
  become: yes
  vars_files:
    - vars/rhel_{{ ansible_distribution_major_version }}.yml
    - vars/engine.yml
  tasks:
    - block:
        - name: register with RHN
          include_role:
            name: oatakan.rhn
          vars:
            repo_channels: "{{ repos.rhv_engine }}"
          when: ansible_distribution == 'RedHat'

        - name: disable update of ansible package (only install)
          lineinfile:
            path: /etc/yum.conf
            create: yes
            line: 'installonlypkgs=ansible'
            state: present
          when: ansible_distribution == 'RedHat'

        - name: only allow one package limit
          lineinfile:
            path: /etc/yum.conf
            create: yes
            line: 'installonly_limit=1'
            state: present
          when: ansible_distribution == 'RedHat'

        # this is needed temporarily until ovirt-engine package is updated
#        - name: exclude ansible-2.9.19*,ansible-2.9.20*,ansible-2.9.21*,ansible-2.9.22*
#          lineinfile:
#            path: /etc/yum.conf
#            create: yes
#            line: 'exclude=ansible-2.9.19*,ansible-2.9.20*,ansible-2.9.21*,ansible-2.9.22*'
#            state: present
#          when: ansible_distribution == 'RedHat'

        - include_role:
            name: "{{ role_name }}"
          loop_control:
            loop_var: role_name
          loop:
            - hosts-file
            - common
            - ovirt.engine-setup
            - ovirt-engine-config
            - ovirt-host-vdsm-hooks
            - qemu-gpu-passthrough
            - ovirt-post-install

      always:
        - include_role:
            name: oatakan.rhn
          vars:
            role_action: unregister
          when:
            - ansible_distribution == 'RedHat'
            - not (rhn_offline | default(false)) | bool