---

- hosts: all
  become: yes
  vars_files:
    - vars/rhel_{{ ansible_distribution_major_version }}.yml
    - vars/host.yml

  pre_tasks:
    - name: Login to oVirt
      ovirt_auth:
        url: "{{ engine_url }}"
        username: "{{ engine_user }}"
        password: "{{ engine_password }}"
        ca_file: "{{ engine_cafile | default(omit) }}"
        insecure: "{{ engine_insecure | default(true) }}"
      tags:
        - always

  tasks:
    - include_role:
        name: ovirt-engine-export-local-nfs

    - name: ensure local storage dir exists
      file:
        path: /data
        state: directory
        owner: vdsm
        group: kvm

    - block:
        - name: register with RHN
          include_role:
            name: oatakan.rhn
          vars:
            repo_channels: "{{ repos.rhv_engine }}"
          when: ansible_distribution == 'RedHat'

        - name: add support for non RHEL/CentOS/Fedora EL distros
          replace:
            path: /usr/share/ovirt-engine/ansible-runner-service-project/project/roles/ovirt-host-deploy-facts/tasks/host-os.yml
            regexp: '^(.*)CentOS(.*)$'
            replace: '\1{{ ansible_distribution }}\2'
          ignore_errors: yes
          when:
            - ansible_distribution != 'RedHat'
            - ansible_distribution != 'CentOS'
            - ansible_distribution != 'Fedora'

        - include_role:
            name: ovirt.ovirt.infra
      rescue:
        # retry the same role
        - include_role:
            name: ovirt.ovirt.infra

      always:
        - include_role:
            name: oatakan.rhn
          vars:
            role_action: unregister
          when:
            - ansible_distribution == 'RedHat'
            - not (rhn_offline | default(false)) | bool

        - block:
            - name: reboot system
              reboot:

            - name: Login to oVirt
              ovirt_auth:
                url: "{{ engine_url }}"
                username: "{{ engine_user }}"
                password: "{{ engine_password }}"
                ca_file: "{{ engine_cafile | default(omit) }}"
                insecure: "{{ engine_insecure | default(true) }}"
          when: add_hosts is changed

    - name: remove the default cluster
      ovirt_cluster:
        auth: "{{ ovirt_auth }}"
        name: Default
        state: absent

    - name: remove the default datacenter
      ovirt_datacenter:
        auth: "{{ ovirt_auth }}"
        name: Default
        state: absent

    - name: add nofilter vnic profile
      ovirt_vnic_profile:
        auth: "{{ ovirt_auth }}"
        name: ovirtmgmt_nofilter
        network: ovirtmgmt
        data_center: "{{ data_center_name }}"
        qos: ""
        custom_properties: ""
        network_filter: ""

    # ovirt-imageio service needed on both engine and hosts, this role fixes and allows engine and host to colocate
    - include_role:
        name: ovirt-imageio-fix-self-hosted
      when: (ovirt_engine_setup_version | default(4.4)) is version('4.4', '>=')

    - include_role:
        name: ovirt.image-template

  post_tasks:
    - name: Logout from oVirt
      ovirt_auth:
        state: absent
        ovirt_auth: "{{ ovirt_auth }}"
      tags:
        - always