---
## This playbook deploys the whole application stack in this site.  

- hosts: all
  become: yes
  become_user: root
  vars:
    ovirt_engine_config:
      -
        key: "UserDefinedVMProperties"
        value: "qemu_cmdline=^.*$"
        version: "4.1"
  roles:
    - ansible-role-rhn
    - bertvv.dnsmasq
    - rhevm-qe-automation.ovirt-engine-deploy/roles/ovirt-common
    - rhevm-qe-automation.ovirt-engine-deploy/roles/ovirt-engine-install-packages
    - rhevm-qe-automation.ovirt-engine-deploy/roles/ovirt-engine-setup
    - rhevm-qe-automation.ovirt-engine-deploy/roles/ovirt-engine-config