---
## This playbook deploys the whole application stack in this site.  

- hosts: all
  become: yes
  become_user: root
  roles:
    - rhv-common
    - ovirt-host-vdsm-hooks
    - qemu-gpu-passthrough