---
## This playbook deploys the whole application stack in this site.  

- hosts: all
  become: yes
  become_user: root
  vars:
    #ovirt_repositories_ovirt_release_rpm: http://resources.ovirt.org/pub/yum-repo/ovirt-master-release.rpm
    ovirt_engine_setup_version: '4.2'
    ovirt_engine_setup_organization: 'of.ovirt.engine.com'
    ovirt_engine_setup_admin_password: "{{ ovirt_engine_setup_admin_password }}"
    ovirt_repositories_ovirt_release_rpm: 'http://resources.ovirt.org/pub/yum-repo/ovirt-release42.rpm'
    ovirt_engine_config:
      -
        key: "UserDefinedVMProperties"
        value: "qemu_cmdline=^.*$"
        version: "4.2"
  roles:
    - ovirt.ovirt.repositories
    - ovirt.engine-setup
    - rhevm-qe-automation.ovirt-engine-deploy/roles/ovirt-engine-config