---

- hosts: all
  become: yes
  vars:
    #ovirt_repositories_ovirt_release_rpm: http://resources.ovirt.org/pub/yum-repo/ovirt-master-release.rpm
    ovirt_engine_setup_version: '4.3'
    ovirt_engine_setup_organization: '{{ ansible_fqdn }}'
    ovirt_engine_setup_admin_password: '{{ ansible_password | default(ansible_ssh_password) | b64encode | b64decode }}'
    ovirt_repositories_ovirt_release_rpm: 'http://resources.ovirt.org/pub/yum-repo/ovirt-release43.rpm'
    ovirt_engine_setup_provider_ovn_configure: no
    ovirt_engine_config:
      -
        key: "UserDefinedVMProperties"
        value: "qemu_cmdline=^.*$"
        version: "{{ ovirt_engine_setup_version }}"
  tasks:
    - name: set hosts file
      include_role:
        name: hosts-file

    - name: set up ovirt repositories
      include_role:
        name: ovirt.repositories
      when: ansible_distribution != 'RedHat'

    - name: enable javapackages-tools module
      command: dnf module enable {{ item }} -y
      loop:
        - javapackages-tools
        - pki-deps
      when:
        - ansible_distribution != 'RedHat'
        - ansible_distribution_major_version|int == 8

    - block:

        - name: set repos for 7.x
          set_fact:
            repo_channels:
              - rhel-7-server-rpms
              - rhel-7-server-supplementary-rpms
              - rhel-7-server-rhv-{{ ovirt_engine_setup_version }}-manager-rpms
              - rhel-7-server-rhv-4-manager-tools-rpms
              - rhel-7-server-ansible-2-rpms
              - jb-eap-7.2-for-rhel-7-server-rpms
              - rhel-7-server-rhv-4-mgmt-agent-rpms
          when:
            - ansible_distribution == 'RedHat'
            - ansible_distribution_major_version|int == 7

        - name: register with RHN
          include_role:
            name: oatakan.rhn
          when: ansible_distribution == 'RedHat'

        - include_role:
            name: "{{ role_name }}"
          loop_control:
            loop_var: role_name
          loop:
            - ovirt.engine-setup
            - ovirt-engine-config
            - ovirt-host-vdsm-hooks
            - qemu-gpu-passthrough
            - ovirt-post-install

      always:

        - include_role:
            name: oatakan.rhn
          vars:
            role_action: unregister
          when:
            - ansible_distribution == 'RedHat'
            - not (rhn_offline | default(false)) | bool

#  roles:
#    - hosts-file
#    - ovirt.repositories
#    #- ovn-setup
#    - role: ovirt.engine-setup
#      ovirt_engine_setup_provider_ovn_configure: no
#    #- ovirt-ansible-engine-setup
#    - ovirt-engine-config
#    - ovirt-host-vdsm-hooks
#    - qemu-gpu-passthrough
#    - ovirt-post-install