---
## This playbook deploys the whole application stack in this site.  

- hosts: all
  become: yes
  vars:
    engine_url: https://{{ ovirt_engine_fqdn | default(ansible_fqdn) }}/ovirt-engine/api
    engine_user: admin@internal
    engine_password: "{{ ansible_password }}"
    engine_cafile: /etc/pki/ovirt-engine/ca.pem

    data_center_name: mydatacenter
    compatibility_version: 4.2

    clusters:
      - name: production
        cpu_type: Intel Conroe Family
        profile: production

    hosts:
      - name: "{{ ansible_host }}"
        address: "{{ ansible_host }}"
        cluster: production
        password: "{{ ansible_password }}"

  pre_tasks:
    - name: Login to oVirt
      ovirt_auth:
        url: "{{ engine_url }}"
        username: "{{ engine_user }}"
        password: "{{ engine_password }}"
        ca_file: "{{ engine_cafile | default(omit) }}"
        insecure: "{{ engine_insecure | default(true) }}"
      tags:
        - always

  roles:
    - oVirt.infra

  post_tasks:
    - name: Logout from oVirt
      ovirt_auth:
        state: absent
        ovirt_auth: "{{ ovirt_auth }}"
      tags:
        - always