---

- hosts: all
  become: yes
  vars:
    #ovirt_repositories_ovirt_release_rpm: http://resources.ovirt.org/pub/yum-repo/ovirt-master-release.rpm
    ovirt_engine_setup_version: '4.3'
    ovirt_engine_setup_organization: '{{ ansible_fqdn }}'
    ovirt_engine_setup_admin_password: "{{ ansible_password }}"
    ovirt_repositories_ovirt_release_rpm: 'http://resources.ovirt.org/pub/yum-repo/ovirt-release43.rpm'
    ovirt_engine_config:
      -
        key: "UserDefinedVMProperties"
        value: "qemu_cmdline=^.*$"
        version: "4.3"
  roles:
    - hosts-file
    - ovirt.repositories
    - ovn-setup
    - ovirt.engine-setup
    #- ovirt-ansible-engine-setup
    - rhevm-qe-automation.ovirt-engine-deploy/roles/ovirt-engine-config
    - ovirt-host-vdsm-hooks
    - qemu-gpu-passthrough