---

- hosts: all
  become: yes
  vars:
    #ovirt_repositories_ovirt_release_rpm: http://resources.ovirt.org/pub/yum-repo/ovirt-master-release.rpm
    ovirt_engine_setup_version: '4.3'
    ovirt_engine_setup_organization: '{{ ansible_fqdn }}'
    ovirt_engine_setup_admin_password: '{{ ansible_password | default(ansible_ssh_password) | b64encode | b64decode }}'
    ovirt_repositories_ovirt_release_rpm: 'http://resources.ovirt.org/pub/yum-repo/ovirt-release43.rpm'
    ovirt_engine_setup_provider_ovn_configure: no
    ovirt_engine_config:
      - key: "UserDefinedVMProperties"
        value: "qemu_cmdline=^.*$"
        version: "{{ ovirt_engine_setup_version }}"
  tasks:
    - name: set hosts file
      include_role:
        name: hosts-file

    # this is needed temporarily until shim package is updated
    # see: https://bugzilla.redhat.com/show_bug.cgi?id=1861977
    - name: exclude shim
      lineinfile:
        path: /etc/yum.conf
        create: yes
        line: 'exclude=shim*'
        state: present
      when: ansible_distribution_major_version|int == 8

    - name: set up ovirt repositories
      include_role:
        name: ovirt.repositories
      when: ansible_distribution != 'RedHat'

    - name: enable required modules (CentOS)
      command: dnf module enable {{ item }} -y
      args:
        warn: false
      loop:
        - javapackages-tools
        - pki-deps
        - postgresql:12
      when:
        - ansible_distribution != 'RedHat'
        - ansible_distribution_major_version|int == 8

    - name: enable required modules (RedHat)
      command: dnf module enable {{ item }} -y
      args:
        warn: false
      loop:
        - pki-deps
        - postgresql:12
      when:
        - ansible_distribution == 'RedHat'
        - ansible_distribution_major_version|int == 8

    - name: reset virt (RedHat)
      command: yum module reset virt -y
      args:
        warn: false
      when:
        - ansible_distribution == 'RedHat'
        - ansible_distribution_major_version|int == 8

    - name: enable virt module (RedHat)
      command: dnf module enable virt:8.2 -y
      args:
        warn: false
      when:
        - ansible_distribution == 'RedHat'
        - ansible_distribution_major_version|int == 8

    - name: distro sync (RedHat)
      command: yum distro-sync -y
      args:
        warn: false
      when:
        - ansible_distribution == 'RedHat'
        - ansible_distribution_major_version|int == 8

    - block:

        - name: set repos for 7.x
          set_fact:
            repo_channels:
              - rhel-7-server-rpms
              - rhel-7-server-supplementary-rpms
              - rhel-7-server-rhv-{{ ovirt_engine_setup_version }}-manager-rpms
              - rhel-7-server-rhv-4-manager-tools-rpms
              - rhel-7-server-ansible-2-rpms
              - jb-eap-7.2-for-rhel-7-server-rpms
              - rhel-7-server-rhv-4-mgmt-agent-rpms
          when:
            - ansible_distribution == 'RedHat'
            - ansible_distribution_major_version|int == 7

        - name: set repos for 8.x
          set_fact:
            repo_channels:
              - rhel-8-for-x86_64-baseos-rpms
              - rhel-8-for-x86_64-appstream-rpms
              - rhv-4-mgmt-agent-for-rhel-8-x86_64-rpms
              - ansible-2.9-for-rhel-8-x86_64-rpms
              - advanced-virt-for-rhel-8-x86_64-rpms
          when:
            - ansible_distribution == 'RedHat'
            - ansible_distribution_major_version|int == 8

        - name: register with RHN
          include_role:
            name: oatakan.rhn
          when: ansible_distribution == 'RedHat'

        - name: make sure python3-paramiko is available
          package:
            name: python3-paramiko
          when:
            - ansible_distribution != 'RedHat'
            - ansible_distribution_major_version|int == 8

        - include_role:
            name: "{{ role_name }}"
          loop_control:
            loop_var: role_name
          loop:
            - ovirt.engine-setup
            - ovirt-engine-config
            - ovirt-host-vdsm-hooks
            - qemu-gpu-passthrough
            - ovirt-post-install

      always:

        - include_role:
            name: oatakan.rhn
          vars:
            role_action: unregister
          when:
            - ansible_distribution == 'RedHat'
            - not (rhn_offline | default(false)) | bool