---

- hosts: all
  become: true
  vars_files:
    - vars/rhel_{{ ansible_distribution_major_version }}.yml
    - vars/host.yml

  tasks:
    - include_role:
        name: ovirt-engine-export-local-nfs

    - name: ensure local storage dir exists
      file:
        path: /data
        state: directory
        owner: vdsm
        group: kvm

    - block:
        - name: register with RHN
          include_role:
            name: oatakan.rhn
          vars:
            repo_channels: "{{ repos.rhv_engine }}"
          when: ansible_distribution == 'RedHat'

        - include_role:
            name: oatakan.rhel_upgrade
          vars:
            update_reboot_kernel: true

        - name: add support for non RHEL/CentOS/Fedora EL distros
          replace:
            path: /usr/share/ovirt-engine/ansible-runner-service-project/project/roles/ovirt-host-deploy-facts/tasks/host-os.yml
            regexp: '^(.*)CentOS(.*)$'
            replace: '\1{{ ansible_distribution }}\2'
          ignore_errors: yes
          when:
            - ansible_distribution != 'RedHat'
            - ansible_distribution != 'CentOS'
            - ansible_distribution != 'Fedora'

        # Due to Bug 2091581, while installing the virtualization host you will be missing nmstate-plugin-ovsdb or
        # python3-libnmstate unless you install them from CentOS build nmstate-2.0.0-2.el9.
        # While installing it you need to ensure openvswitch2.15 will be installed instead of any later version.
        - name: install missing packages on rhel 9
          yum:
            name:
              - ovirt-openvswitch
              - https://kojihub.stream.centos.org/kojifiles/packages/nmstate/2.0.0/2.el9/noarch/nmstate-plugin-ovsdb-2.0.0-2.el9.noarch.rpm
              - https://kojihub.stream.centos.org/kojifiles/packages/nmstate/2.0.0/2.el9/noarch/python3-libnmstate-2.0.0-2.el9.noarch.rpm
            disable_gpg_check: true
          when: ansible_distribution_major_version|int == 9

        - name: login to ovirt
          ovirt.ovirt.ovirt_auth:
            url: "{{ engine_url }}"
            username: "{{ engine_user }}"
            password: "{{ engine_password }}"
            ca_file: "{{ engine_cafile | default(omit) }}"
            insecure: "{{ engine_insecure | default(true) }}"
          delegate_to: localhost
          become: false
          tags:
            - always

        - include_role:
            name: ovirt.ovirt.infra
            apply:
              delegate_to: localhost
              become: false
      rescue:
        # retry the same role
        - include_role:
            name: ovirt.ovirt.infra
            apply:
              delegate_to: localhost
              become: false

      always:
        - include_role:
            name: oatakan.rhn
          vars:
            role_action: unregister
          when:
            - ansible_distribution == 'RedHat'
            - not (rhn_offline | default(false)) | bool

        - name: reboot system
          reboot:

        - name: login to ovirt
          ovirt.ovirt.ovirt_auth:
            url: "{{ engine_url }}"
            username: "{{ engine_user }}"
            password: "{{ engine_password }}"
            ca_file: "{{ engine_cafile | default(omit) }}"
            insecure: "{{ engine_insecure | default(true) }}"
          delegate_to: localhost
          become: false
          register: login_ovirt
          until: login_ovirt is success
          delay: 3
          retries: 10

    - name: remove the default cluster
      ovirt.ovirt.ovirt_cluster:
        auth: "{{ ovirt_auth }}"
        name: Default
        state: absent
      delegate_to: localhost
      become: false

    - name: remove the default datacenter
      ovirt.ovirt.ovirt_datacenter:
        auth: "{{ ovirt_auth }}"
        name: Default
        state: absent
      delegate_to: localhost
      become: false

    - name: add nofilter vnic profile
      ovirt.ovirt.ovirt_vnic_profile:
        auth: "{{ ovirt_auth }}"
        name: ovirtmgmt_nofilter
        network: ovirtmgmt
        data_center: "{{ data_center_name }}"
      delegate_to: localhost
      become: false

    # ovirt-imageio service needed on both engine and hosts, this role fixes and allows engine and host to colocate
    - include_role:
        name: ovirt-imageio-fix-self-hosted
        apply:
          delegate_to: localhost
          become: false
      when: (ovirt_engine_setup_version | default(4.5)) is version('4.5', '>=')

    - block:
        - include_role:
            name: ovirt.ovirt.image_template
            apply:
              delegate_to: localhost
              become: false
      rescue:
        - debug:
            msg: "ignoring any template errors..."

  post_tasks:
    - name: logout from ovirt
      ovirt.ovirt.ovirt_auth:
        state: absent
        ovirt_auth: "{{ ovirt_auth }}"
      delegate_to: localhost
      become: false
      tags:
        - always