- name: undeploy node on kubevirt
  hosts: all
  become: no
  gather_facts: no
  connection: local
  vars_files:
    - node-config/node-kubevirt.yml
  roles:
    - role: ansible-role-kubevirt
      role_action: deprovision
      delegate_to: localhost
      run_once: yes