- name: undeploy node on ovirt
  hosts: all
  become: no
  gather_facts: no
  connection: local
  vars_files:
    - node-config/node-ovirt.yml
  roles:
    - role: ansible-role-ovirt
      role_action: deprovision
      delegate_to: localhost
      run_once: yes