---
- name: Remove systems
  hosts: all
  gather_facts: False
  connection: local
  become: no
  vars:
    provider: vmware
    provider_role: "{{ provider }}"
    config_name: "{{ provider }}"
  vars_files:
    - node-config/node-{{ config_name }}.yml

  roles:
    - role: ansible-role-{{ provider_role | default(provider) }}
      role_action: deprovision
      delegate_to: localhost
      run_once: yes