- name: undeploy node on vmware
  hosts: all
  become: no
  gather_facts: no
  connection: local
  vars_files:
    - node-config/node-vmware.yml
  roles:
    - role: ansible-role-vmware
      role_action: deprovision
      delegate_to: localhost
      run_once: yes