- src: bertvv.dnsmasq

- src: https://github.com/oatakan/ansible-role-rhn
  version: origin/master

#- src: ovirt.ovirt-ansible-roles

- src: ovirt.repositories

- src: ovirt.engine-setup

- src: rhevm-qe-automation.ovirt-engine-deploy

- src: ovirt.infra

- src: ovirt.image-template