- src: bertvv.dnsmasq

- src: https://github.com/oatakan/ansible-role-rhn
  version: origin/master

- src: ovirt.ovirt-ansible-roles2

- src: ovirt.repositories2

- src: ovirt.engine-setup2

- src: rhevm-qe-automation.ovirt-engine-deploy
