---
config_dir: /etc/ansible-ovirt
engine_fqdn: "{{ ansible_fqdn }}"
engine_username: admin@ovirt
admin_password: changeme
dc_name: Default
storage_type: nfs

iso_storage_name: iso_domain
iso_storage_address: "{{ ansible_default_ipv4.address }}"
iso_storage_path: /export/iso

data_storage_name: data_domain
data_storage_address: "{{ ansible_default_ipv4.address }}"
data_storage_path: /export/data

export_storage_name: export_domain
export_storage_address: "{{ ansible_default_ipv4.address }}"
export_storage_path: /export/import_export

create_export_domain: yes

create_iso_domain: yes
