---
- name: install nfs-utils packages
  yum:
    name: nfs-utils
    state: latest

- name: add kvm group
  group:
    name: kvm
    gid: 36
    state: present

- name: add vdsm user
  user:
    name: vdsm
    uid: 36
    group: kvm
    state: present

- name: Create directory
  file:
    path: "{{ item }}"
    owner: vdsm
    group: kvm
    state: directory
    mode: 0755
  with_items:
    - "{{ iso_storage_path }}"
    - "{{ data_storage_path }}"
    - "{{ export_storage_path }}"

- name: copy nfs exports configuration
  template: src=etc/exports.j2 dest=/etc/exports owner=root group=root

- name: ensure nfs is running and enabled
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop:
    - "{{ nfs_service_name }}"
    - rpcbind

- name: run exportfs
  shell: exportfs -ra

- name: add firewall rules for nfs
  firewalld:
    service: "{{ item }}"
    zone: public
    permanent: true
    state: enabled
  with_items:
    - nfs
    - mountd
    - rpc-bind

- name: reload firewall rules
  shell: firewall-cmd --reload

