---
- include_tasks: selinux.yml
  when: apply_selinux_policy|bool

# this seems to be needed with ovirt 4.5.4 as pip and netaddr is not installed with the latest version of python
- include_tasks: netaddr.yml

# check to see if this is required in GA
#- name: disable nmstate on 4.4 pre
#  copy:
#    content: |
#      [vars]
#      net_nmstate_enabled=false
#    dest: /etc/vdsm/vdsm.conf.d/99-disable-nmstate.conf
#  when:
#    - ovirt_engine_setup_version is version('4.4', '==')
#    - ('release4.4-pre' in ovirt_repositories_ovirt_release_rpm)