- name: gather facts about ansible python version
  shell: ansible --version | awk '/python version/ {print $NF}' | sed 's/[()]//g'
  register: ansible_python_version_output

- name: extract ansible python path
  set_fact:
    local_ansible_python_path: "{{ ansible_python_version_output.stdout | replace('\n', '') | regex_replace('([0-9]+\\.[0-9]+).*', '\\1') }}"

- name: set pip version
  set_fact:
    python_version_short: "{{ local_ansible_python_path | regex_replace('.*/python([0-9]+\\.[0-9]+).*', '\\1') }}"

- name: ensure pip is installed
  become: true
  shell: "{{ local_ansible_python_path }} -m ensurepip --upgrade"

- name: find pip binary
  find:
    paths:
      - /usr/bin
      - /usr/local/bin
    patterns: "pip{{ python_version_short }}"
  register: pip_binary_location

- name: ensure netaddr pip package is installed
  become: true
  pip:
    name: netaddr
    executable: "{{ pip_binary_location.files[0].path }}"
    state: present