---
iso_storage_name: iso_domain
iso_storage_address: "{{ ansible_default_ipv4.address }}"
iso_storage_path: /export/iso

data_storage_name: data_domain
data_storage_address: "{{ ansible_default_ipv4.address }}"
data_storage_path: /export/data

export_storage_name: export_domain
export_storage_address: "{{ ansible_default_ipv4.address }}"
export_storage_path: /export/import_export

