---

# this is needed temporarily until shim package is updated
# see: https://bugzilla.redhat.com/show_bug.cgi?id=1861977
#- name: exclude shim
#  lineinfile:
#    path: /etc/yum.conf
#    create: yes
#    line: 'exclude=shim*'
#    state: present

- name: enable required modules
  command: dnf module enable {{ item }} -y
  loop:
    - pki-deps
    - postgresql:12
    - mod_auth_openidc:2.3
    - nodejs:14

- block:
    - include_tasks: RedHat_8.yml
      when: ansible_distribution == 'RedHat'

    - include_tasks: CentOS_8.yml
      when: ansible_distribution != 'RedHat'
  when: ansible_distribution_major_version == '8'
