---

- name: set up ovirt repositories
  include_role:
    name: ovirt.ovirt.repositories (<4.5)
  when:
    - ansible_distribution != 'RedHat'
    - ansible_distribution_major_version is version('4.5', '<')

- block:
    - name: install centos-stream-release
      yum:
        name: "{{ centos_stream_release_rpm_urls[ansible_distribution_major_version + '_stream'] }}"
      when: ansible_distribution == 'RedHat'

    - block:
        - name: install dnf-plugins-core
          yum:
            name: dnf-plugins-core

        - name: disable extras
          command: dnf config-manager --set-disabled extras
          args:
            warn: false
      when: ansible_distribution == 'Rocky'

    - include_tasks: repo_{{ ansible_distribution_major_version }}.yml

    - name: enable ovirt repositories (4.5)
      package:
        name: centos-release-ovirt45
        state: latest

    - name: ensure dnf nfvsigdist var exists
      copy:
        dest: /etc/dnf/vars/nfvsigdist
        content: '{{ ansible_distribution_major_version }}-stream'

    - name: distro sync
      command: dnf distro-sync --nobest -y
      args:
        warn: false

  when:
    - ansible_distribution_major_version is version('4.5', '>=')
    - ansible_distribution_major_version in ['8','9']

- include_tasks: el_8.yml
  when: ansible_distribution_major_version|int == 8

- include_tasks: time.yml