---

- name: enable SHA1 on RHEL 9 (<4.5)
  ansible.builtin.command: update-crypto-policies --set LEGACY
  when:
    - ansible_distribution_major_version|int > 8
    - ovirt_engine_setup_version is version('4.5', '<')

- name: set up ovirt repositories (<4.5)
  ansible.builtin.include_role:
    name: ovirt.ovirt.repositories
  vars:
    ovirt_repositories_ovirt_release_rpm_gpg: https://plain.resources.ovirt.org/pub/keys/RPM-GPG-ovirt-v3
  when:
    - ansible_distribution != 'RedHat'
    - ovirt_engine_setup_version is version('4.5', '<')

- name: prepare host for ovirt engine setup
  ansible.builtin.include_tasks: el_{{ ansible_distribution_major_version | string | default('10') }}.yml

- name: include time configuration tasks
  ansible.builtin.include_tasks: time.yml