---

- name: set up ovirt repositories
  include_role:
    name: ovirt.ovirt.repositories
  when:
    - ansible_distribution != 'RedHat'
    - ansible_distribution_major_version is version('4.5', '<')

- include_tasks: el_8.yml
  when: ansible_distribution_major_version|int == 8

- include_tasks: el_9.yml
  when: ansible_distribution_major_version|int == 9

- include_tasks: time.yml