---

- name: set up ovirt repositories
  include_role:
    name: ovirt.repositories
  when: ansible_distribution != 'RedHat'

- include_tasks: el_8.yml
  when: ansible_distribution_major_version|int == 8