---

- name: add Centos 9 Stream Extras common repo
  ansible.builtin.yum_repository:
    name: c9s-extras-common
    description: CentOS Stream 9 - Extras packages
    file: CentOS-Stream-Extras-common
    metalink: https://mirrors.centos.org/metalink?repo=centos-extras-sig-extras-common-9-stream&arch=$basearch&protocol=https,http
    enabled: yes
    gpgcheck: yes
    gpgkey: https://www.centos.org/keys/RPM-GPG-KEY-CentOS-SIG-Extras

- name: ensure dnf stream var exists
  copy:
    dest: /etc/dnf/vars/stream
    content: '9-stream'