---
- name: get pci slot
  shell: lspci -mm | grep "{{ pci_device_key_name }}" | cut -d " " -f 1
  register: pci_slot

- name: add consoleblank to grub
  lineinfile:
    state: present
    dest: /etc/default/grub
    backrefs: yes
    regexp: '^(GRUB_CMDLINE_LINUX=(?!.*\ consoleblank)\"[^\"]+)(\".*)'
    line: '\1 consoleblank={{ consoleblank_timeout }}\2'
  when: set_consoleblank|bool

- include_tasks: gpu.yml
  when: pci_slot.stdout | length > 0

- name: add iommu=pt to grub
  lineinfile:
    state: present
    dest: /etc/default/grub
    backrefs: yes
    regexp: '^(GRUB_CMDLINE_LINUX=(?!.*\ iommu)\"[^\"]+)(\".*)'
    line: '\1 iommu=pt\2'

- name: add intel_iommu to grub
  lineinfile:
    state: present
    dest: /etc/default/grub
    backrefs: yes
    regexp: '^(GRUB_CMDLINE_LINUX=(?!.*intel_iommu)\"[^\"]+)(\".*)'
    line: '\1 intel_iommu=on\2'
  when: ('Intel' in ansible_processor[1])

- name: add amd_iommu to grub
  lineinfile:
    state: present
    dest: /etc/default/grub
    backrefs: yes
    regexp: '^(GRUB_CMDLINE_LINUX=(?!.*amd_iommu)\"[^\"]+)(\".*)'
    line: '\1 amd_iommu=on\2'
  when: ('AMD' in ansible_processor[1])

- include: redhat.yml
  when: ansible_os_family == 'RedHat'

- name: reboot system
  reboot: