---
- name: get pci slot
  shell: lspci -mm | grep "{{ device_key_name }}" | cut -d " " -f 1
  register: pci_slot

- include_tasks: gpu.yml
  when: pci_slot.stdout | length > 0

- name: add intel_iommu to grub
  lineinfile:
    state: present
    dest: /etc/default/grub
    backrefs: yes
    regexp: '^(GRUB_CMDLINE_LINUX=(?!.*intel_iommu)\"[^\"]+)(\".*)'
    line: '\1 intel_iommu=on\2'

- include: redhat.yml
  when: ansible_os_family == 'RedHat'

- name: reboot system
  reboot: