---
- name: check if legacy BIOS
  stat:
    path: /boot/grub2/grub.cfg
  register: legacy_bios_grub_config

- name: regenerate grub config
  shell: grub2-mkconfig -o /boot/grub2/grub.cfg
  when: legacy_bios_grub_config.stat.exists

- name: regenerate grub config
  shell: grub2-mkconfig -o {{ grub_config_file.redhat }}
  when: legacy_bios_grub_config.stat.exists == False and ansible_distribution == 'RedHat'

- name: regenerate grub config
  shell: grub2-mkconfig -o {{ grub_config_file.centos }}
  when: legacy_bios_grub_config.stat.exists == False and ansible_distribution == 'CentOS'

- include_tasks: edk2.yml