---

- name: link ovirt-imageio engine config to higher priority
  file:
    src: /etc/ovirt-imageio/conf.d/50-engine.conf
    dest: /etc/ovirt-imageio/conf.d/60-engine.conf
    state: link
  notify:
    - restart ovirt-imageio service
    - test ovirt-imageio engine

- name: ensure ovirt-imageio-host config dir exists
  file:
    path: /etc/ovirt-imageio-host/conf.d/
    state: directory

- name: Find *-vdsm.conf file
  find:
    paths: /etc/ovirt-imageio/conf.d
    patterns: '*-vdsm.conf'
  register: vdsm_conf

- name: link ovirt-imageio host config to new dir
  file:
    src: "{{ vdsm_conf.files[0].path }}"
    dest: /etc/ovirt-imageio-host/conf.d/{{ vdsm_conf.files[0].path | basename }}
    state: link
  notify:
    - enable and start ovirt-imageio-host service
    - test ovirt-imageio host
  when: vdsm_conf.matched > 0

- name: copy new service for vdsm
  copy:
    src: ovirt-imageio-host.service
    dest: /etc/systemd/system/ovirt-imageio-host.service
  notify:
    - enable and start ovirt-imageio-host service
    - test ovirt-imageio host

- name: flush handlers here
  meta: flush_handlers