---

- name: check to see if we are running on the engine
  stat:
    path: /etc/ovirt-imageio/conf.d/50-engine.conf
  register: check_ovirt_imageio_engine

- include_tasks: fix.yml
  when: check_ovirt_imageio_engine.stat.exists