---
- name: set hostname to inventory name
  hostname:
    name: "{{ inventory_hostname }}"
  when: set_hostname is defined and set_hostname

- name: build hosts file
  lineinfile:
    dest: /etc/hosts
    regexp: '.*{{ item }}$'
    line: "{{ hostvars[item].ansible_default_ipv4.address }} {{ item }}"
    state: present
  when: (hostvars[item].ansible_default_ipv4.address is defined) and (hostvars[item].ec2_private_dns_name is not defined)
  with_items: "{{ play_hosts }}"

- name: build hosts file
  lineinfile:
    dest: /etc/hosts
    regexp: '.*{{ item }}$'
    line: "{{ hostvars[item].ansible_default_ipv4.address }} {{ hostvars[item].ec2_private_dns_name }}"
    state: present
  when: (hostvars[item].ansible_default_ipv4.address is defined) and (hostvars[item].ec2_private_dns_name is defined)
  with_items: "{{ play_hosts }}"
