---

- name: install hooks
  yum:
    name:
      - vdsm-hook-qemucmdline # for extended cmd args
      - vdsm-hook-macspoof # for nested vms
      - vdsm-hook-nestedvt # for nested vms
    state: latest
  when: ansible_distribution != 'RedHat'