---

- name: install hooks (CentOS)
  yum:
    name:
      - vdsm-hook-qemucmdline # for extended cmd args
      - vdsm-hook-nestedvt
    state: latest
  when: ansible_distribution != 'RedHat' or ovirt_engine_setup_version is version('4.5', '>=')

- name: install hooks (RHEL)
  yum:
    name:
      - "{{ vdsm_hook_qemucmdline_rpm['rhel'+ ansible_distribution_major_version] }}" # for extended cmd args
      - vdsm-hook-nestedvt
    disable_gpg_check: yes
    state: latest
  when:
    - ovirt_engine_setup_version is version('4.5', '<')
    - ansible_distribution == 'RedHat'